import { Suspense } from "react";
import Loading from "./loading";
import TopRated from "./components/TopRated";
import NowPlaying from "./components/NowPlaying";
import Trending from "./components/Trending";

interface IImageSizes {
  large: string,
  small: string
}

export const metadata = {
  title: 'TMDB movies homepage',
  description: 'Generated by TMDB movies crew, homepage',
}

const token = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkZmI3MGU5ZjI1NjBjYmJjOTA2N2ZkZTliNDczMmM1NCIsInN1YiI6IjYyNjA3Yjg0YWY0MzI0MDA2NWQ0MTZlZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.lW33QlBQHdGVGJZY9nYM-6FBwAX942didSxzfXzqJ4s';
export const imageBaseUrl = 'https://image.tmdb.org/t/p';

export const apiOptions = {
  baseUrl: 'https://api.themoviedb.org/3',
  headers: {
    'Authorization': `Bearer ${token}`,
    'accept': 'application/json'
  }
}

export const imageSize: IImageSizes = {
  large: 'w500',
  small: 'w250'
}

// TODO: Fetch the data here

export default async function page() {

  return (
    <div className="flex">
      <h1 className="sr-only"> TMDB movies homepage </h1>
      <h2> Trending </h2>
      <Suspense fallback={<Loading />}>
        <Trending />
      </Suspense>
      <h2>Now playing</h2>
      <Suspense fallback={<Loading />}>
        <NowPlaying />
      </Suspense>
      <h2>Top rated</h2>
      <Suspense fallback={<Loading />}>
        <TopRated />
      </Suspense>
    </div>
  )
}